# Generated by Django 4.1.4 on 2022-12-06 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0005_alter_usercourserelation_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercourserelation',
            name='course',
        ),
        migrations.AddField(
            model_name='usercourserelation',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainsite.course'),
        ),
    ]
